name: BuildDevSecOps

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full history scan
      # Secret Scanning
      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      # Code linting
      - name: Install ESLint v8 (classic config)
        run: npm install eslint@8 --save-dev
      - name: Install sarif formatter for ESLint
        run: npm install eslint-formatter-sarif --save-dev

      - name: Run ESLint and generate SARIF report
        run: npx eslint . -f node_modules/eslint-formatter-sarif/index.js -o eslint-report.sarif || true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-report.sarif



