name: BuildDevSecOps

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full history scan
      # Secret Scanning
      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      # Code linting

      - name: Download PMD
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd.zip -d pmd
          mv pmd/pmd-bin-6.55.0 pmd-bin

     # ✅ PMD (Code lint, code quality)
      - name: Run PMD
        run: |
          ./pmd-bin/bin/run.sh pmd \
            -d src \
            -R category/java/bestpractices.xml \
            -f html \
            -r pmd-report.html
        continue-on-error: true

      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: pmd-report.html



