name: BuildDevSecOps

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full history scan

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # ✅ TruffleHog (Secrets Scanner)
      - name: Run TruffleHog v3
        run: |
          docker run --rm -v ${{ github.workspace }}:/src ghcr.io/trufflesecurity/trufflehog:latest \
          filesystem --directory /src --only-verified --json > trufflehog-results.json
        continue-on-error: true
          
      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json