name: BuildDevSecOps

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full history scan
      # Secret Scanning
      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      # Code linting

      - name: Run ESLint via Docker and generate SARIF
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            node:20-slim /bin/bash -c "
              npm install eslint eslint-formatter-sarif --no-save &&
              npx eslint . -f node_modules/eslint-formatter-sarif/index.js -o eslint-report.sarif || true"



